name: Browser tests

on:
    push:
        branches:
            - main
            - '[0-9]+.[0-9]+'
    pull_request: ~

jobs:
    admin-ui:
        name: "Admin UI tests"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@behat-php-config
        with:
            project-edition: 'oss'
            ci-scripts-branch: 'behat-php-config'
            test-setup-phase-1: '--profile=regression --suite=setup-oss --mode=standard'
            test-suite: "--mode=standard --profile=browser --suite=admin-ui-full --tags='~@broken&&~@IbexaDXP'"
            multirepository: true
            timeout: 40
        secrets: inherit
    examples:
        name: "BehatBundle examples"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@behat-php-config
        with:
            project-edition: 'oss'
            ci-scripts-branch: 'behat-php-config'
            test-suite:  '--mode=standard --profile=service --suite=examples'
        secrets: inherit

    page-builder:
        name: "Page Builder tests"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: 'experience'
            test-suite: '--profile=browser --suite=page-builder-full'
            test-setup-phase-1: '--profile=setup --suite=personas --tags=@setup --mode=standard'
            test-setup-phase-2: '--profile=setup --suite=page-builder --tags=@setup --mode=standard'
        secrets: inherit
