services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ibexa\Bundle\Behat\Controller\ExceptionController:
    public: true
  
  ezbehatbundle.controller.exception:
    class: Ibexa\Bundle\Behat\Controller\ExceptionController
    public: true

  Ibexa\Bundle\Behat\Controller\RenderController: ~

  Ibexa\Bundle\Behat\Controller\UnauthenticatedRedirectController: ~

  Ibexa\Bundle\Behat\Controller\CurrentUserDataController: ~
